# DATA CLEANING

In [8]:
import pandas as pd
import numpy as np

In [20]:
data = pd.DataFrame({
    'names' : ['Sahil' , 'Nirjala' , 'Mahesh' , 'Sahil' , np.nan],
    'age' : [28 , np.nan , 34 , 28 , 22],
    'purchase_amt' : [100.5, 85.3, np.nan, 100.5, 50.5],
    'date_of_purchase' : ['2023/12/01', '2023/12/01', '2023/12/02', '2023/12/01', '2023/12/03']
})

display(data)
display(data.info())

     names   age  purchase_amt date_of_purchase
0    Sahil  28.0         100.5       2023/12/01
1  Nirjala   NaN          85.3       2023/12/01
2   Mahesh  34.0           NaN       2023/12/02
3    Sahil  28.0         100.5       2023/12/01
4      NaN  22.0          50.5       2023/12/03

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   names             4 non-null      object
 1   age               4 non-null      float64
 2   purchase_amt      4 non-null      float64
 3   date_of_purchase  5 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

None

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
data[['age','purchase_amt']] = imputer.fit_transform(data[['age','purchase_amt']])

In [23]:
data = data.drop_duplicates()

In [25]:
data.loc[:,'date_of_purchase'] = pd.to_datetime(data['date_of_purchase'])

In [27]:
display(data)
data.info()

     names   age  purchase_amt date_of_purchase
0    Sahil  28.0         100.5       2023-12-01
1  Nirjala  28.0          85.3       2023-12-01
2   Mahesh  34.0          84.2       2023-12-02
4      NaN  22.0          50.5       2023-12-03

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   names             3 non-null      object
 1   age               4 non-null      float64
 2   purchase_amt      4 non-null      float64
 3   date_of_purchase  4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 160.0+ bytes

# DATA INTEGRATION

In [30]:
import pandas as pd

data1 = pd.DataFrame({
    'customer_id': [1, 2, 3],
    'name': ['John', 'Jane', 'Jack'],
    'age': [28, 34, 29]
})

data2 = pd.DataFrame({
    'customer_id': [1, 2, 4],
    'purchase_amount': [100.5, 85.3, 45.0],
    'purchase_date': ['2023/12/01', '2023/12/02', '2023/12/03']
})

merged_data = pd.merge(data1, data2, on='customer_id', how='inner')
merged_data

   customer_id  name  age  purchase_amount purchase_date
0            1  John   28            100.5    2023/12/01
1            2  Jane   34             85.3    2023/12/02

# DATA TRANSFORMATION

In [31]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

data2 = pd.DataFrame({
    'category': ['A', 'B', 'A', 'C', 'B'],
    'numeric_column': [10, 15, 10, 20, 15]
})

scaler = StandardScaler()
data2['scaled_numberic_column'] = scaler.fit_transform(data2[['numeric_column']])

encoder = OneHotEncoder(sparse_output=False)
encoded_data = pd.DataFrame(
    encoder.fit_transform(data2[['category']]),
    columns = encoder.get_feature_names_out(['category']
    )
)
data3 = pd.concat([data2, encoded_data], axis=1)
print(data3)

  category  numeric_column  scaled_numberic_column  category_A  category_B  \
0        A              10               -1.069045         1.0         0.0
1        B              15                0.267261         0.0         1.0
2        A              10               -1.069045         1.0         0.0
3        C              20                1.603567         0.0         0.0
4        B              15                0.267261         0.0         1.0

   category_C
0         0.0
1         0.0
2         0.0
3         1.0
4         0.0

# DATA REDUCTION

In [42]:
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest , chi2
data4 = pd.DataFrame({
    'feature1': [10, 20, 30, 40, 50],
    'feature2': [1, 2, 3, 4, 5],
    'feature3': [100, 200, 300, 400, 500],
    'target' : [0,1,0,1,0]
})

selector = SelectKBest(chi2,k=2)
selected_features = selector.fit_transform(
                    X = data4[['feature1' , 'feature2' , 'feature3']] ,
                    y = data4['target']
)

print('Selected features (SelectKBest):')
print(selected_features)
pca = PCA(n_components=2)
pca_data = pca.fit_transform(data4[['feature1' , 'feature2' , 'feature3']])
print(pca_data)

Selected features (SelectKBest):
[[  1 100]
 [  2 200]
 [  3 300]
 [  4 400]
 [  5 500]]
[[-2.01007463e+02 -2.69618663e-15]
 [-1.00503731e+02  8.98728878e-16]
 [ 0.00000000e+00 -0.00000000e+00]
 [ 1.00503731e+02 -8.98728878e-16]
 [ 2.01007463e+02 -1.79745776e-15]]